<footer class="footer overlay section">
            <!-- Footer Top -->
            <div class="footer-top">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-3 col-md-6 col-12">
                            <!-- About -->
                            <div class="single-widget about">
                                <div class="logo"><a href="#"><a href="./"><img src="assets/images/abu_logo-white.png" alt="#" style="width:90px;"></a></a></div>
                                
                                <?php 
                                if(true) {
                                    ?>
                                    
                                    <h4><?php echo (empty($this->facName)) ? 'Faculty Name' : $this->facName; ?><br></h4>
<p><?php echo (empty($this->instName)) ? 'Institution Name' : $this->instName; ?><br>
Main Campus </p>
                                <?php }else{?>
                                    <p><?php echo $this->abu_mission?></p>
                                <?php } ?>
                                <!--ul class="list">
                                    <li><i class="fa fa-phone"></i>Phone: +123 456-7890 </li>
                                    <li><i class="fa fa-envelope"></i>Email: <a href="mailto:info@youremail.com">Info@youremail.com</a></li>
                                    <li><i class="fa fa-map-o"></i>Address: 211 Ronad, California, Us</li>
                                </ul-->
                            </div>
                            <!--/ End About -->
                        </div>
                        <div class="col-lg-3 col-md-6 col-12">
                            <!-- Useful Links -->
                            <div class="single-widget">
                            <h2>Facilities and Services</h2>
                                <ul>
                                    <li><a href="https://abu.edu.ng/university-health-services"><i class="fa fa-angle-right"></i>University Health Services</a></li>
                                    <li><a href="https://abu.edu.ng/counselling-and-human-development"><i class="fa fa-angle-right"></i>Counselling & Human Dev Centre</a></li>
                                    <li><a href="https://abu.edu.ng/energy-bulk-metering-unit"><i class="fa fa-angle-right"></i>Electricity Bulk Metering Unit</a></li>
                                </ul>
                            </div>
                            <!--/ End Useful Links -->
                        </div>
                        <div class="col-lg-3 col-md-6 col-12">
                            <!-- Latest News -->
                            <div class="single-widget">
                            <h2>Campus Life</h2>
                                <ul>
                                    <li><a href="https://abu.edu.ng/coming-soon"><i class="fa fa-angle-right"></i>Students Representative Council</a></li>
                                    <li><a href="http://portal.abu.edu.ng/"><i class="fa fa-angle-right"></i>Students Campus Accomodation</a></li>
                                    <li><a href="https://abu.edu.ng/coming-soon"><i class="fa fa-angle-right"></i>Students Club and Societies</a></li>
                                    <li><a href="http://hotspot.abu.edu.ng/status"><i class="fa fa-angle-right"></i>ABU Free Wi-Fi Services</a></li>
                                </ul>
                            </div>
                            <!--/ End Latest News -->
                        </div>
                        <div class="col-lg-3 col-md-6 col-12">
                            <!-- Newsletter -->
                            <div class="single-widget">
                                <h2>Other Links</h2>
                                <ul>
                                    <li><a href="http://sbrsabu.org/"><i class="fa fa-angle-right"></i>School of Basic & Remedial Studies </a></li>
                                    <li><a href="http://spgs.abu.edu.ng/"><i class="fa fa-angle-right"></i>School of Post Graduate Studies</a></li>
                                    <li><a href="https://library.abu.edu.ng/"><i class="fa fa-angle-right"></i>University Library</a></li>
                                    <li><a href="https://abu.edu.ng/privacy-policy"><i class="fa fa-angle-right"></i>Privacy Policy</a></li>
                                </ul>
                            </div>
                            <!--/ End Newsletter -->
                        </div>
                    </div>
                </div>
            </div>
            <!--/ End Footer Top -->
            <!-- Footer Bottom -->
            <div class="footer-bottom">
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <div class="bottom-head">
                                <div class="row">
                                    <div class="col-12">
                                        <!-- Social -->
                                        <!--ul class="social">
                                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                            <li><a href="#"><i class="fa fa-youtube"></i></a></li>
                                        </ul-->
                                        <!-- End Social -->
                                        <!-- Copyright -->
                                        <div class="copyright">
                                            <p>Managed by <a href="#">Web Management Unit</a></p>
                                        </div>
                                        <!--/ End Copyright -->
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--/ End Footer Bottom -->
        </footer>
