<footer class="footer overlay section">
			<!-- Footer Top -->
			<div class="footer-top">
				<div class="container">
					<div class="row">
						<div class="col-lg-3 col-md-6 col-12">
							<!-- About -->
							<div class="single-widget about">
								<div class="logo"><a href="#"><a href="./"><img src="assets/images/abu_logo-white.png" alt="#" style="width:90px;"></a></a></div>
								
								<?php 
								if(true){
								?>
									
									<h4><?php echo (empty($this->facName)) ? 'Faculty Name' : $this->facName; ?><br></h4>
<p><?php echo (empty($this->instName)) ? 'Institution Name' : $this->instName; ?><br>
Main Campus <p>
								<?php }else{?>
									<p><?=$this->abu_mission?></p>
								<?php } ?>
								<!--ul class="list">
									<li><i class="fa fa-phone"></i>Phone: +123 456-7890 </li>
									<li><i class="fa fa-envelope"></i>Email: <a href="mailto:info@youremail.com">Info@youremail.com</a></li>
									<li><i class="fa fa-map-o"></i>Address: 211 Ronad, California, Us</li>
								</ul-->
							</div>
							<!--/ End About -->
						</div>
						<div class="col-lg-3 col-md-6 col-12">
							<!-- Useful Links -->
							<div class="single-widget footer-link">
							<a href="https://abu.edu.ng/" target="_blank"><p>News</p></a>
								
							</div>
							<!--/ End Useful Links -->
						</div>
						<div class="col-lg-3 col-md-6 col-12">
							<!-- Latest News -->
							<div class="single-widget footer-link">
							<a href="https://abu.edu.ng/animal-use/" target="_blank"><p>Animal Use</p></a>
							</div>
							<!--/ End Latest News -->
						</div>
						<div class="col-lg-3 col-md-6 col-12">
							<!-- Newsletter -->
							<div class="single-widget footer-link">
								<a href="https://abu.edu.ng/contact-us/" target="_blank"><p>Contact</p></a>
								
							</div>
							<!--/ End Newsletter -->
						</div>
					</div>
				</div>
			</div>
			<!--/ End Footer Top -->
			<!-- Footer Bottom -->
			<div class="footer-bottom">
				<div class="container">
					<div class="row">
						<div class="col-12">
							<div class="bottom-head">
								<div class="row">
									<div class="col-12">
										<!-- Social -->
										<!--ul class="social">
											<li><a href="#"><i class="fa fa-twitter"></i></a></li>
											<li><a href="#"><i class="fa fa-facebook"></i></a></li>
											<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
											<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
											<li><a href="#"><i class="fa fa-youtube"></i></a></li>
										</ul-->
										<!-- End Social -->
										<!-- Copyright -->
										<div class="copyright">
											<p>Managed by <a href="#">Web Management Unit</a></p>
										</div>
										<!--/ End Copyright -->
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!--/ End Footer Bottom -->
		</footer>