<div class="topbar">
				<div class="container">
					<div class="row">
						<div class="col-lg-8 col-12">
							<!-- Contact -->
							<ul class="content">
							<li class="brand-fac text-capitalise" ><a href="<?php echo (empty($this->facName)) ? '#' : $this->facUrl; ?>" ><?php echo (empty($this->facName)) ? 'Faculty Name' : 'Faculty of ' . $this->facName; ?></a> | <a href="https://abu.edu.ng">abu.edu.ng</a></li>
								<!--li><i class="fa fa-phone"></i>123-456-789</li>
								<li><a href="mailto:info@yourdomain.com"><i class="fa fa-envelope-o"></i>contact@yourdomain.com</a></li-->
								<!--li><i class="fa fa-clock-o"></i>Opening: 8:00am - 4:00pm</li-->
								<p class="mobile-name"><?php echo (empty($this->deptName)) ? 'Department Name' : $this->deptName; ?></p>
								<p class="mobile-name--inst"><?php echo (empty($this->instName)) ? 'Institution Name' : $this->instName; ?></p>
							</ul>
							<!-- End Contact -->
						</div>
						<div class="col-lg-4 col-12">
							<!-- Social -->
							<ul class="social">
								<!--li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-google-plus "></i></a></li>
								<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
								<li><a href="#"><i class="fa fa-behance"></i></a></li>
								<li><a href="#"><i class="fa fa-dribbble"></i></a></li>
								<li><a href="#"><i class="fa fa-youtube"></i></a></li-->
								<!--li><a href="http://staff.abu.edu.ng" target="_blank"><i class="">Staff Portal</i></a></li-->
								<li><a href="http://portal.abu.edu.ng" target="_blank"><i class="">Student Portal</i></a></li>
								<li><a href="https://spgs.abu.edu.ng/" target="_blank"><i class="">PG Portal</i></a></li>
								<li><a href="http://moodle.abu.edu.ng" target="_blank"><i class="">Moodle</i></a></li>
								<li><a href="http://library.abu.edu.ng" target="_blank"><i class="">Library</i></a></li>
							</ul>
							<!-- End Social -->
						</div>
					</div>
				</div>
			</div>