<div class="header-inner">
				<div class="container">
					<div class="row">
						<div class="col-lg-1 col-md-1 col-12">
							<div class="logo">
								<a href="./"><img src="assets/images/abu_logo.png" alt="#" style=""></a>
							</div>
							<div class="mobile-menu"></div>
						</div>
						<div class="col-lg-11 col-md-11 col-12">
							<!-- Header Widget -->
							
								<div class="department-label text-left" style="position:relative;top:22%">
									<h3><?php echo (empty($this->deptName)) ? 'Department Name' : $this->deptName; ?></h3>
									<h5><?php echo (empty($this->instName)) ? 'Institution Name' : $this->instName; ?></h5>
								</div>
								
							
							<!--/ End Header Widget -->
						</div>
					</div>
				</div>
			</div>