<section class="blog section">
			<div class="container">
				<div class="row">
					<div class="col-12">
						<div class="section-title">
							<h2>Latest <span>News</span></h2>
							<p>Mauris at varius orci. Vestibulum interdum felis eu nisl pulvinar, quis ultricies nibh. Sed ultricies ante vitae laoreet sagittis. In pellentesque viverra purus. Sed risus est, molestie nec hendrerit hendreri </p>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-12">
						<div class="blog-slider">
							<!-- Single Blog -->
							<div class="single-blog">
								<div class="blog-head overlay">
									<div class="date">
										<h4>10<span>May</span></h4>
									</div>
									<img src="assets/images/800x550.png" alt="#">
								</div>
								<div class="blog-content">
									<h4 class="blog-title"><a href="blog-single.html">Our Student Have sit amet egestas</a></h4>
									<div class="blog-info">
										<a href="#"><i class="fa fa-user"></i>By: Admin</a>
										<a href="#"><i class="fa fa-list"></i>Learning</a>
										<a href="#"><i class="fa fa-heart-o"></i>53K</a>
									</div>
									<p>Vivamus volutpat eros pulvinar velit laoreet, sit amet egestas erat dignissim. Et harum quidem rerum facilis est et expedita distinctio</p>
									<div class="button">
										<a href="blog-single.html" class="btn">Read More<i class="fa fa-angle-double-right"></i></a>
									</div>
								</div>
							</div>
							<!-- End Single Blog -->
							<!-- Single Blog -->
							<div class="single-blog">
								<div class="blog-head overlay">
									<div class="date">
										<h4>05<span>May</span></h4>
									</div>
									<img src="assets/images/800x550.png" alt="#">
								</div>
								<div class="blog-content">
									<h4 class="blog-title"><a href="blog-single.html">Our teachers egestas erat dignissim</a></h4>
									<div class="blog-info">
										<a href="#"><i class="fa fa-user"></i>By: Admin</a>
										<a href="#"><i class="fa fa-list"></i>Academic</a>
										<a href="#"><i class="fa fa-heart-o"></i>33K</a>
									</div>
									<p>Vivamus volutpat eros pulvinar velit laoreet, sit amet egestas erat dignissim. Et harum quidem rerum facilis est et expedita distinctio</p>
									<div class="button">
										<a href="blog-single.html" class="btn">Read More<i class="fa fa-angle-double-right"></i></a>
									</div>
								</div>
							</div>
							<!-- End Single Blog -->
							<!-- Single Blog -->
							<div class="single-blog">
								<div class="blog-head overlay">
									<div class="date">
										<h4>15<span>Mar</span></h4>
									</div>
									<img src="assets/images/800x550.png" alt="#">
								</div>
								<div class="blog-content">
									<h4 class="blog-title"><a href="blog-single.html">We are Proffesional Have velit Landon</a></h4>
									<div class="blog-info">
										<a href="#"><i class="fa fa-user"></i>By: Admin</a>
										<a href="#"><i class="fa fa-list"></i>Knowledge</a>
										<a href="#"><i class="fa fa-heart-o"></i>11K</a>
									</div>
									<p>Vivamus volutpat eros pulvinar velit laoreet, sit amet egestas erat dignissim. Et harum quidem rerum facilis est et expedita distinctio</p>
									<div class="button">
										<a href="blog-single.html" class="btn">Read More<i class="fa fa-angle-double-right"></i></a>
									</div>
								</div>
							</div>
							<!-- End Single Blog -->
							<!-- Single Blog -->
							<div class="single-blog">
								<div class="blog-head overlay">
									<div class="date">
										<h4>10<span>Mar</span></h4>
									</div>
									<img src="http://via.placeholder.com/800x550" alt="#">
								</div>
								<div class="blog-content">
									<h4 class="blog-title"><a href="blog-single.html">Our Student Have sit amet egestas</a></h4>
									<div class="blog-info">
										<a href="#"><i class="fa fa-user"></i>By: Admin</a>
										<a href="#"><i class="fa fa-list"></i>Learning</a>
										<a href="#"><i class="fa fa-heart-o"></i>53K</a>
									</div>
									<p>Vivamus volutpat eros pulvinar velit laoreet, sit amet egestas erat dignissim. Et harum quidem rerum facilis est et expedita distinctio</p>
									<div class="button">
										<a href="blog-single.html" class="btn">Read More<i class="fa fa-angle-double-right"></i></a>
									</div>
								</div>
							</div>
							<!-- End Single Blog -->
							<!-- Single Blog -->
							<div class="single-blog">
								<div class="blog-head overlay">
									<div class="date">
										<h4>25<span>Feb</span></h4>
									</div>
									<img src="http://via.placeholder.com/800x550" alt="#">
								</div>
								<div class="blog-content">
									<h4 class="blog-title"><a href="blog-single.html">Our teachers egestas erat dignissim</a></h4>
									<div class="blog-info">
										<a href="#"><i class="fa fa-user"></i>By: Admin</a>
										<a href="#"><i class="fa fa-list"></i>Academic</a>
										<a href="#"><i class="fa fa-heart-o"></i>33K</a>
									</div>
									<p>Vivamus volutpat eros pulvinar velit laoreet, sit amet egestas erat dignissim. Et harum quidem rerum facilis est et expedita distinctio</p>
									<div class="button">
										<a href="blog-single.html" class="btn">Read More<i class="fa fa-angle-double-right"></i></a>
									</div>
								</div>
							</div>
							<!-- End Single Blog -->
							<!-- Single Blog -->
							<div class="single-blog">
								<div class="blog-head overlay">
									<div class="date">
										<h4>28<span>Feb</span></h4>
									</div>
									<img src="http://via.placeholder.com/800x550" alt="#">
								</div>
								<div class="blog-content">
									<h4 class="blog-title"><a href="blog-single.html">We are Proffesional Have velit Landon</a></h4>
									<div class="blog-info">
										<a href="#"><i class="fa fa-user"></i>By: Admin</a>
										<a href="#"><i class="fa fa-list"></i>Knowledge</a>
										<a href="#"><i class="fa fa-heart-o"></i>11K</a>
									</div>
									<p>Vivamus volutpat eros pulvinar velit laoreet, sit amet egestas erat dignissim. Et harum quidem rerum facilis est et expedita distinctio</p>
									<div class="button">
										<a href="blog-single.html" class="btn">Read More<i class="fa fa-angle-double-right"></i></a>
									</div>
								</div>
							</div>
							<!-- End Single Blog -->
							<!-- Single Blog -->
							<div class="single-blog">
								<div class="blog-head overlay">
									<div class="date">
										<h4>03<span>Jan</span></h4>
									</div>
									<img src="http://via.placeholder.com/800x550" alt="#">
								</div>
								<div class="blog-content">
									<h4 class="blog-title"><a href="blog-single.html">Our Student Have sit amet egestas</a></h4>
									<div class="blog-info">
										<a href="#"><i class="fa fa-user"></i>By: Admin</a>
										<a href="#"><i class="fa fa-list"></i>Learning</a>
										<a href="#"><i class="fa fa-heart-o"></i>53K</a>
									</div>
									<p>Vivamus volutpat eros pulvinar velit laoreet, sit amet egestas erat dignissim. Et harum quidem rerum facilis est et expedita distinctio</p>
									<div class="button">
										<a href="blog-single.html" class="btn">Read More<i class="fa fa-angle-double-right"></i></a>
									</div>
								</div>
							</div>
							<!-- End Single Blog -->
						</div>
					</div>
				</div>
			</div>
		</section>