<section class="courses section-bg section">
			<div class="container">
				<div class="row">
					<div class="col-12 wow zoomIn">
						<div class="section-title">
							<h2>Popular <span>Courses</span> We Offer</h2>
							<p>Mauris at varius orci. Vestibulum interdum felis eu nisl pulvinar, quis ultricies nibh. Sed ultricies ante vitae laoreet sagittis. In pellentesque viverra purus. Sed risus est, molestie nec hendrerit hendreri </p>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-12">
						<div class="course-slider">
							<!-- Single Course -->
							<div class="single-course">
								<div class="course-head overlay">
									<img src="http://via.placeholder.com/370x250" alt="#">
									<a href="course-single.html" class="btn"><i class="fa fa-link"></i></a>
								</div>
								<div class="single-content">
									<h4><a href="course-single.html"><span>Commerce</span>Business Management</a></h4>
									<p>Vivamus volutpat eros pulvinar velit laoreet, sit amet egestas erat dignissim. Lorem ipsum dolor sit amet, consectetur adipiscing elit aenean </p>
								</div>
								<div class="course-meta">
									<div class="meta-left">
										<span><i class="fa fa-users"></i>36 Seat</span>
										<span><i class="fa fa-clock-o"></i>2 Years</span>
									</div>
									<span class="price">$350</span>
								</div>
							</div>
							<!--/ End Single Course -->
							<!-- Single Course -->
							<div class="single-course">
								<div class="course-head overlay">
									<img src="http://via.placeholder.com/370x250" alt="#">
									<a href="course-single.html" class="btn"><i class="fa fa-link"></i></a>
								</div>
								<div class="single-content">
									<h4><a href="course-single.html"><span>Science</span>Software Engineer</a></h4>
									<p>Vivamus volutpat eros pulvinar velit laoreet, sit amet egestas erat dignissim. Lorem ipsum dolor sit amet, consectetur adipiscing elit aenean </p>
								</div>
								<div class="course-meta">
									<div class="meta-left">
										<span><i class="fa fa-users"></i>20 Seat</span>
										<span><i class="fa fa-clock-o"></i>1 Years</span>
									</div>
									<span class="price">$590</span>
								</div>
							</div>
							<!--/ End Single Course -->
							<!-- Single Course -->
							<div class="single-course">
								<div class="course-head overlay">
									<img src="http://via.placeholder.com/370x250" alt="#">
									<a href="course-single.html" class="btn"><i class="fa fa-link"></i></a>
								</div>
								<div class="single-content">
									<h4><a href="course-single.html"><span>Science</span>Electrical Management</a></h4>
									<p>Vivamus volutpat eros pulvinar velit laoreet, sit amet egestas erat dignissim. Lorem ipsum dolor sit amet, consectetur adipiscing elit aenean </p>
								</div>
								<div class="course-meta">
									<div class="meta-left">
										<span><i class="fa fa-users"></i>49 Seat</span>
										<span><i class="fa fa-clock-o"></i>2 Years</span>
									</div>
									<span class="price">$140</span>
								</div>
							</div>
							<!--/ End Single Course -->
							<!-- Single Course -->
							<div class="single-course">
								<div class="course-head overlay">
									<img src="http://via.placeholder.com/370x250" alt="#">
									<a href="course-single.html" class="btn"><i class="fa fa-link"></i></a>
								</div>
								<div class="single-content">
									<h4><a href="course-single.html"><span>Commerce</span>Business Management</a></h4>
									<p>Vivamus volutpat eros pulvinar velit laoreet, sit amet egestas erat dignissim. Lorem ipsum dolor sit amet, consectetur adipiscing elit aenean </p>
								</div>
								<div class="course-meta">
									<div class="meta-left">
										<span><i class="fa fa-users"></i>36 Seat</span>
										<span><i class="fa fa-clock-o"></i>2 Years</span>
									</div>
									<span class="price">$350</span>
								</div>
							</div>
							<!--/ End Single Course -->
							<!-- Single Course -->
							<div class="single-course">
								<div class="course-head overlay">
									<img src="http://via.placeholder.com/370x250" alt="#">
									<a href="course-single.html" class="btn"><i class="fa fa-link"></i></a>
								</div>
								<div class="single-content">
									<h4><a href="course-single.html"><span>Science</span>Software Engineer</a></h4>
									<p>Vivamus volutpat eros pulvinar velit laoreet, sit amet egestas erat dignissim. Lorem ipsum dolor sit amet, consectetur adipiscing elit aenean </p>
								</div>
								<div class="course-meta">
									<div class="meta-left">
										<span><i class="fa fa-users"></i>20 Seat</span>
										<span><i class="fa fa-clock-o"></i>1 Years</span>
									</div>
									<span class="price">$590</span>
								</div>
							</div>
							<!--/ End Single Course -->
							<!-- Single Course -->
							<div class="single-course">
								<div class="course-head overlay">
									<img src="http://via.placeholder.com/370x250" alt="#">
									<a href="course-single.html" class="btn"><i class="fa fa-link"></i></a>
								</div>
								<div class="single-content">
									<h4><a href="course-single.html"><span>Science</span>Electrical Management</a></h4>
									<p>Vivamus volutpat eros pulvinar velit laoreet, sit amet egestas erat dignissim. Lorem ipsum dolor sit amet, consectetur adipiscing elit aenean </p>
								</div>
								<div class="course-meta">
									<div class="meta-left">
										<span><i class="fa fa-users"></i>49 Seat</span>
										<span><i class="fa fa-clock-o"></i>2 Years</span>
									</div>
									<span class="price">$140</span>
								</div>
							</div>
							<!--/ End Single Course -->
						</div>
					</div>
				</div>
			</div>
		</section>