<section class="cta" data-stellar-background-ratio="0.5">
			<div class="container">
				<div class="row">
					<div class="col-lg-5 offset-lg-6 col-12">
						<div class="cta-inner overlay">
							<div class="text-content">
								<h2>We Focus On Brands, Products & Campaigns</h2>
								<p>Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore cum. Coluta nobis est eligendi optio cumque nihil impedit quo minusd quod maxime placeat facere possimus, omnis voluptas assumenda est. Our friendly support team is standing by to help you every step of the way.</p>
								<div class="button">
									<a class="btn primary wow fadeInUp" href="contact.html" >Register Now</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>