<section class="events section">
			<div class="container">
				<div class="row">
					<div class="col-12 wow zoomIn">
						<div class="section-title">
							<h2>Upcoming <span>Events</span></h2>
							<p>Mauris at varius orci. Vestibulum interdum felis eu nisl pulvinar, quis ultricies nibh. Sed ultricies ante vitae laoreet sagittis. In pellentesque viverra purus. Sed risus est, molestie nec hendrerit hendreri </p>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-12">
						<div class="event-slider">
							<!-- Single Event -->
							<div class="single-event">
								<div class="head overlay">
									<img src="http://via.placeholder.com/690x465" alt="#">
									<a href="http://via.placeholder.com/690x465" data-fancybox="photo" class="btn"><i class="fa fa-search"></i></a>
								</div>
								<div class="event-content">
									<div class="meta"> 
										<span><i class="fa fa-calendar"></i>05 June 2018</span>
										<span><i class="fa fa-clock-o"></i>12.00-5.00PM</span>
									</div>
									<h4><a href="event-single.html">Freshers Day Reception 2018</a></h4>
									<p>Lorem ipsum dolor sit amet, consectetur adipi sicing elit, sed do eiusmod tempor incididunt</p>
									<div class="button">
										<a href="event-single.html" class="btn">Join Event</a>
									</div>
								</div>
							</div>
							<!--/ End Single Event -->
							<!-- Single Event -->
							<div class="single-event">
								<div class="head overlay">
									<img src="http://via.placeholder.com/690x465" alt="#">
									<a href="http://via.placeholder.com/690x465" data-fancybox="photo" class="btn"><i class="fa fa-search"></i></a>
								</div>
								<div class="event-content">
									<div class="meta">
										<span><i class="fa fa-calendar"></i>03 July 2018</span>
										<span><i class="fa fa-clock-o"></i>03.20-5.20PM</span>
									</div>
									<h4><a href="event-single.html">Best Student Award 2018</a></h4>
									<p>Lorem ipsum dolor sit amet, consectetur adipi sicing elit, sed do eiusmod tempor incididunt</p>
									<div class="button">
										<a href="event-single.html" class="btn">Join Event</a>
									</div>
								</div>
							</div>
							<!--/ End Single Event -->
							<!-- Single Event -->
							<div class="single-event">
								<div class="head overlay">
									<img src="http://via.placeholder.com/690x465" alt="#">
									<a href="http://via.placeholder.com/690x465" data-fancybox="photo" class="btn"><i class="fa fa-search"></i></a>
								</div>
								<div class="event-content">
									<div class="meta">
										<span><i class="fa fa-calendar"></i>15 Dec 2018</span>
										<span><i class="fa fa-clock-o"></i>12.30-5.30PM</span>
									</div>
									<div class="title">
										<h4><a href="event-single.html">Student Workshop</a></h4>
										<p>Lorem ipsum dolor sit amet, consectetur adipi sicing elit, sed do eiusmod tempor incididunt</p>
									</div>
									<div class="button">
										<a href="event-single.html" class="btn">Join Event</a>
									</div>
								</div>
							</div>
							<!--/ End Single Event -->
						</div>
					</div>
				</div>
			</div>
		</section>