<?php
    $news = isset($this->news) && !empty($this->news) ? $this->news : [];
    $config = $this->config;
    //var_dump($config);exit;
?>
<section class="blog section" style="background:#ccc">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="section-title">
                            <h2>Latest <span>News</span></h2>
                            <!--p>Mauris at varius orci. Vestibulum interdum felis eu nisl pulvinar, quis ultricies nibh. Sed ultricies ante vitae laoreet sagittis. In pellentesque viverra purus. Sed risus est, molestie nec hendrerit hendreri </p-->
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="blog-slider">
        
                        <?php if (count($news) > 0) {?>
                            <?php foreach ($news as $singleNews) : ?>
                            
                                
                            <!-- Single Blog -->
                            <div class="single-blog">
                                <div class="blog-head overlay">
                                    <!--div class="date">
                                        <h4>10<span>May</span></h4>
                                    </div-->
                                    <img src="<?php echo $config['host'].$singleNews->getImageLink()?>" alt="<?php echo $singleNews->getTitle()?>" style="height:270px">
                                </div>
                                <div class="blog-content">
                                    <h4 class="blog-title" title="<?php echo $singleNews->getTitle()?>"><a href="#"><?php echo substr($singleNews->getTitle(), 0, 35); ?></a></h4>
                                    <div class="blog-info">
                                        <!--a href="#"><i class="fa fa-user"></i>By: </a-->
                                        <a href="#"><i class="fa fa-list"></i><?php echo $singleNews->getCategory();?></a>
                                        <!--a href="#"><i class="fa fa-heart-o"></i>53K</a-->
                                    </div>
                                    <p>
                                    <?php 
                                        //echo substr($singleNews->getBody(), 0, 70);
                                    ?>
                                    </p>
                                    <div class="button">
                                        <a href="<?php echo $config['host'].$singleNews->getUrl(); ?>" class="btn" target="_blank">Read More<i class="fa fa-angle-double-right"></i></a>
                                    </div>
                                </div>
                            </div>
                            <!-- End Single Blog -->
                            
                            
                            <?php endforeach ?>
                        <?php } else { ?>
                            <p>No News </p>
                        <?php } ?>


                        </div>
                    </div>
                </div>
            </div>
        </section>
