<section class="home-slider">
			<div class="slider-active">
				<!-- Single Slider -->
				<div class="single-slider overlay" style="background-image:url('assets/images/slide1.JPG')" data-stellar-background-ratio="0.5">
					<div class="container">
						<div class="row">
							<div class="col-lg-8 col-md-8 col-12">
								<div class="slider-text">
									<h1>Undergraduate and postgraduate <span> programmes</span></h1>
									<p></p>
									<div class="button">
										<a href="undergraduate.php" class="btn primary">DVM Programme</a>
										<a href="about-us.php" class="btn">About Us</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!--/ End Single Slider -->
				<!-- Single Slider -->
				<!--div class="single-slider overlay" style="background-image:url('assets/images/slide2.JPG')" data-stellar-background-ratio="0.5">
					<div class="container">
						<div class="row">
							<div class="col-lg-8 offset-lg-2 col-md-8 offset-md-2 col-12">
								<div class="slider-text text-center">
									<h1>Enthusiastic Students'</h1>
									<p></p>
									<div class="button">
									<a href="undergraduate.php" class="btn primary">Undergraduate</a>
										<a href="about-us.php" class="btn">About Us</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div-->
				<!--/ End Single Slider -->
				<!-- Single Slider -->
				<div class="single-slider overlay" style="background-image:url('assets/images/slide4.JPG')" data-stellar-background-ratio="0.5">
					<div class="container">
						<div class="row">
							<div class="col-lg-8 offset-lg-4 col-md-8 offset-md-4 col-12">
								<div class="slider-text text-right">
								<h1>We Offer <span>Veterinary Services</span></h1>
									<p>Our opening hours, 8 AM - 4 PM (Clinics) and 4 PM - 10 PM (Calls) Monday - Sunday </p>
									<div class="button">
									<a href="undergraduate.php" class="btn primary">DVM Programme</a>
										<a href="about-us.php" class="btn">About Us</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!--/ End Single Slider -->
			</div>
		</section>