<section class="team section">
			<div class="container">
				<div class="row">
					<div class="col-12 wow zoomIn">
						<div class="section-title">
							<h2>Our Awesome <span>Teachers</span></h2>
							<p>Mauris at varius orci. Vestibulum interdum felis eu nisl pulvinar, quis ultricies nibh. Sed ultricies ante vitae laoreet sagittis. In pellentesque viverra purus. Sed risus est, molestie nec hendrerit hendreri </p>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-3 col-md-6 col-12 wow fadeIn" data-wow-delay="0.4s">
						<!-- Single Team -->
						<div class="single-team">
							<img src="http://via.placeholder.com/275x370" alt="#">
							<div class="team-hover">
								<h4>Rohan Jonson<span>Associate Professor</span></h4>
								<p>cumque nihil impedit quo minusid quod maxime placeat facere possimus</p>
								<ul class="social">
									<li><a href="#"><i class="fa fa-facebook"></i></a></li>
									<li><a href="#"><i class="fa fa-twitter"></i></a></li>
									<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
									<li><a href="#"><i class="fa fa-youtube"></i></a></li>
								</ul>
							</div>
						</div>
						<!--/ End Single Team -->
					</div>
					<div class="col-lg-3 col-md-6 col-12 wow fadeIn" data-wow-delay="0.6s">
						<!-- Single Team -->
						<div class="single-team active">
							<img src="http://via.placeholder.com/275x370" alt="#">
							<div class="team-hover">
								<h4 class="name">Ian Harvey<span class="work">Web Programmer</span></h4>
								<p>cumque nihil impedit quo minusid quod maxime placeat facere possimus</p>
								<ul class="social">
									<li><a href="#"><i class="fa fa-facebook"></i></a></li>
									<li><a href="#"><i class="fa fa-twitter"></i></a></li>
									<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
									<li><a href="#"><i class="fa fa-youtube"></i></a></li>
								</ul>
							</div>
						</div>
						<!--/ End Single Team -->
					</div>
					<div class="col-lg-3 col-md-6 col-12 wow fadeIn" data-wow-delay="0.8s">
						<!-- Single Team -->
						<div class="single-team">
							<img src="http://via.placeholder.com/275x370" alt="#">
							<div class="team-hover">
								<h4 class="name">Lusfat Roman<span class="work">Software Engineer</span></h4>
								<p>cumque nihil impedit quo minusid quod maxime placeat facere possimus</p>
								<ul class="social">
									<li><a href="#"><i class="fa fa-facebook"></i></a></li>
									<li><a href="#"><i class="fa fa-twitter"></i></a></li>
									<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
									<li><a href="#"><i class="fa fa-youtube"></i></a></li>
								</ul>
							</div>
						</div>
						<!--/ End Single Team -->
					</div>
					<div class="col-lg-3 col-md-6 col-12 wow fadeIn" data-wow-delay="1s">
						<!-- Single Team -->
						<div class="single-team">
							<img src="http://via.placeholder.com/275x370" alt="#">
							<div class="team-hover">
								<h4 class="name">Nalpamb Bold<span class="work">JS Developer</span></h4>
								<p>cumque nihil impedit quo minusid quod maxime placeat facere possimus</p>
								<ul class="social">
									<li><a href="#"><i class="fa fa-facebook"></i></a></li>
									<li><a href="#"><i class="fa fa-twitter"></i></a></li>
									<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
									<li><a href="#"><i class="fa fa-youtube"></i></a></li>
								</ul>
							</div>
						</div>
						<!--/ End Single Team -->
					</div>
				</div>
			</div>
		</section>