<!DOCTYPE html>
<html class="no-js" lang="zxx">
    <head>
        <!-- Meta -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="keywords" content="SITE KEYWORDS HERE" />
        <meta name="description" content="">
        <meta name='copyright' content=''>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Favicon -->
         <!--link rel="icon" type="image/png" href="assets/images/favicon.png"-->
        <link rel="apple-touch-icon" sizes="180x180" href="assets/images/favicon/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="assets/images/favicon/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="assets/images/favicon/favicon-16x16.png">
        <link rel="manifest" href="assets/images/favicon/site.webmanifest">
        <link rel="mask-icon" href="assets/images/favicon/safari-pinned-tab.svg" color="#5bbad5">
        <meta name="msapplication-TileColor" content="#da532c">
        <meta name="theme-color" content="#ffffff">

        <!-- Title -->
        <title><?php echo $this->vPage == 'index' ? 'Home | ': $this->title . ' | '; echo $this->deptName . ' | ' . $this->instName ;  ?></title>
        
       
        <!-- Web Font -->
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900" rel="stylesheet">


        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="assets/css/bootstrap.min.css">
        <!-- Font Awesome CSS -->
        <link rel="stylesheet" href="assets/css/font-awesome.min.css">
        <!-- Fancy Box CSS -->
        <link rel="stylesheet" href="assets/css/jquery.fancybox.min.css">
        <!-- Owl Carousel CSS -->
        <link rel="stylesheet" href="assets/css/owl.carousel.min.css">
        <link rel="stylesheet" href="assets/css/owl.theme.default.min.css">
        <!-- Animate CSS -->
        <link rel="stylesheet" href="assets/css/animate.min.css">
        <!-- Slick Nav CSS -->
        <link rel="stylesheet" href="assets/css/slicknav.min.css">
        <!-- Magnific Popup -->
        <link rel="stylesheet" href="assets/css/magnific-popup.css">
        
        <!-- Learedu Stylesheet -->
        <link rel="stylesheet" href="assets/css/normalize.css">
        <link rel="stylesheet" href="assets/style.css">
        <link rel="stylesheet" href="assets/css/responsive.css">

        <!-- Custom Stylesheet -->
        <link rel="stylesheet" href="assets/css/department.css">
        
        <!-- Learedu Color -->
        <link rel="stylesheet" href="assets/css/color/colorcustom.css">
        <!--<link rel="stylesheet" href="assets/css/color/color1.css">-->
        <!--<link rel="stylesheet" href="assets/css/color/color2.css">-->
        <!--<link rel="stylesheet" href="assets/css/color/color3.css">-->
        <!--<link rel="stylesheet" href="assets/css/color/color4.css">-->
        <!--<link rel="stylesheet" href="assets/css/color/color5.css">-->
        <!--<link rel="stylesheet" href="assets/css/color/color6.css">-->
        <!--<link rel="stylesheet" href="assets/css/color/color7.css">-->
        <!--<link rel="stylesheet" href="assets/css/color/color8.css">-->
    </head>
    <body>
    
        <!-- Book Preloader -->
        
        <!--/ End Book Preloader -->
    
        <!-- Header -->
        <?php $this->include("_header.phtml",[]) ?>
        <!-- End Header -->
        
        <!-- Content -->
        
        <!--/ End Content -->
        <!-- Specific page content goes here -->
    <?php $this->content(); ?>
        <!-- Footer -->
    <?php $this->include("_footer--alt.phtml") ?>
        <!--/ End Footer -->
        
        <!-- Jquery JS-->
        <script src="assets/js/jquery.min.js"></script>
        <script src="assets/js/jquery-migrate.min.js"></script>
        <!-- Popper JS-->
        <script src="assets/js/popper.min.js"></script>
        <!-- Bootstrap JS-->
        <script src="assets/js/bootstrap.min.js"></script>
        <!-- Jquery Steller JS -->
        <script src="assets/js/jquery.stellar.min.js"></script>
        <!-- Particle JS -->
        <script src="assets/js/particles.min.js"></script>
        <!-- Fancy Box JS-->
        <script src="assets/js/facnybox.min.js"></script>
        <!-- Magnific Popup JS-->
        <script src="assets/js/jquery.magnific-popup.min.js"></script>
        <!-- Masonry JS-->
        <script src="assets/js/masonry.pkgd.min.js"></script>
        <!-- Circle Progress JS -->
        <script src="assets/js/circle-progress.min.js"></script>
        <!-- Owl Carousel JS-->
        <script src="assets/js/owl.carousel.min.js"></script>
        <!-- Waypoints JS-->
        <script src="assets/js/waypoints.min.js"></script>
        <!-- Slick Nav JS-->
        <script src="assets/js/slicknav.min.js"></script>
        <!-- Counter Up JS -->
        <script src="assets/js/jquery.counterup.min.js"></script>
        <!-- Easing JS-->
        <script src="assets/js/easing.min.js"></script>
        <!-- Wow Min JS-->
        <script src="assets/js/wow.min.js"></script>
        <!-- Scroll Up JS-->
        <script src="assets/js/jquery.scrollUp.min.js"></script>
        <!-- Google Maps JS -->
        <script src="http://maps.google.com/maps/api/js?key=AIzaSyC0RqLa90WDfoJedoE3Z_Gy7a7o8PCL2jw"></script>
        <script src="assets/js/gmaps.min.js"></script>
        <!--script src="assets/js/map-script.js"></script-->
        <!-- Main JS-->
        <script src="assets/js/main.js"></script>
    </body>
</html>
