<?php 
$advisers = $this->advisers;

?>

<section class="faq page section">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="section-title">
                            <h2><span> <?php echo $this->title?> </span></h2>
                            <p></p>
                        </div>
                    </div>
                </div>
                <?php
                
                ?>
                <div class="row">
                    <div class="col-lg-10 offset-lg-1 col-12">
                        <div class="faq-content">
                            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                                <?php if (count($advisers) > 0) :?>
                                    <?php $i = 0;?>
                                    <?php foreach ($advisers as $key => $value) : ?>
                            <div class="panel panel-default <?php echo $i==0 ? 'active':'' ?>">
                                    <!-- Single Faq -->
                                    <div class="faq-heading"  id="w<?php echo $key?>">
                                        <h4 class="faq-title">
                                            <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#<?php echo $key?>"><?php echo $key?></a>
                                        </h4>
                                    </div>
                                    <div id="<?php echo $key?>" class="panel-collapse collapse <?php echo $i==0 ? 'show':'' ?>" role="tabpanel" aria-labelledby="w<?php echo $key?>">
                                    <div class="faq-body">
                                        <?php 
                                        if(is_array($value)) :
                                            ?>
                                            
                                            <?php
                                            if($key=='Research') :
                                                ?>
                                                <?php foreach ($value as $v) : ?>
                                                <?php echo isset($v) && !empty($v) ? '<li>Head of Research : '.$v.'</li>':''; ?>
                                                <?php endforeach; ?>
                                            <?php endif; ?>

                                            <?php
                                            if($key=='Laboratory') :
                                                ?>
                                                <?php foreach ($value as $v => $s) : ?>
                                                <?php echo isset($s['lab']) && !empty($s['lab']) && isset($s['coordinator']) && !empty($s['coordinator']) ? '<li> '.$s['lab'].' : '.$s['coordinator'].'</li>':''; ?>
                                                <?php endforeach; ?>
                                            <?php endif; ?>

                                            <?php
                                            if($key=='Other') :
                                                ?>
                                                <?php foreach ($value as $v => $s) : ?>
                                                <?php echo isset($s['position']) && !empty($s['position']) && isset($s['coordinator']) && !empty($s['coordinator']) ? '<li> '.$s['position'].' : '.$s['coordinator'].'</li>':''; ?>
                                                <?php endforeach; ?>
                                            <?php endif; ?>

                                        <?php endif; ?>
                                    </div>
                                    </div>
                                    <!--/ End Single Faq -->
                                </div>
                                        <?php $i = $i + 1;?>
                                    <?php endforeach; ?>
                                <?php else: ?>
                            <p>No information </p>
                                <?php endif; ?>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--/ End Faqs -->
