    <?php 
        $contact = isset($this->contact) && !empty($this->contact) ? $this->contact:'';
    ?>
    <!-- Contact Us -->
    <section id="contact" class="contact section">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="section-title">
                            <h2><span>Contact</span> Information</h2>
                            <p></p>
                        </div>
                    </div>
                </div>
                <div class="contact-head">
                    <div class="row">
                    <div class="col-lg-6 col-md-6 col-12">
                            <div class="contact-map">
                                <!-- Map -->
                                <!--div id="map"></div-->
                                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3914.488478690196!2d7.653036714804119!3d11.151422842067703!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb8a8bddb61b0e090!2sDepartment%20of%20Physics!5e0!3m2!1sen!2sng!4v1607955306165!5m2!1sen!2sng" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                                <!--/ End Map -->
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-12">
                            
                            <!-- Contact-Info -->
        <?php if (isset($contact['address']) && !empty($contact['address'])) : ?>
                            <div class="contact-info">
                                <div class="icon"><i class="fa fa-map"></i></div>
                                <h3>Location</h3>
                                <p><?php echo $contact['address']?></p>
                            </div>
        <?php endif; ?>
                        
                        
                            <!-- Contact-Info -->
        <?php if (isset($contact['email']) && !empty($contact['email'])) : ?>
                            <div class="contact-info">
                                <div class="icon"><i class="fa fa-envelope"></i></div>
                                <h3>Email Address</h3>
                                <a href="mailto:<?php echo $contact['email']?>"><?php echo $contact['email']?></a>
                            </div>
        <?php endif; ?>
                        
                        
                            <!-- Contact-Info -->
        <?php if (isset($contact['phone']) && !empty($contact['phone'])) : ?>
                            <div class="contact-info">
                                <div class="icon"><i class="fa fa-phone"></i></div>
                                <h3>Get in Touch</h3>
                                <p><?php echo $contact['phone']?></p>
                            </div>
        <?php endif; ?>
                        
                        </div>
                    </div>
                </div>
                <div class="contact-bottom">
                    <div class="row">
                        
                    </div>
                </div>
            </div>
        </section>
        <!--/ End Contact Us -->
