<?php
    $news = isset($this->news) && !empty($this->news) ? $this->news : [];
    $config = $this->config;
    //var_dump($config);exit;
?>
    <!-- Blogs -->
    <section class="blog b-archives section">
            <div class="container">

            <div class="row">
                    <div class="col-12">
                        <div class="section-title">
                            <h2><span><?php echo $this->title?></span></h2>
                        </div>
                    </div>
                </div>

                <div class="row masonry">
                    
                    <?php if (count($news) > 0) {?>
                        <?php foreach ($news as $singleNews) : ?>
                            
                                <div class="col-lg-4 col-12 grid-item">
                            <!-- Single Blog -->
                            <div class="single-blog">
                                <div class="blog-head overlay">
                                    <!--div class="date">
                                        <h4>10<span>May</span></h4>
                                    </div-->
                                    <img src="<?php echo $config['host'].$singleNews->getImageLink()?>" alt="<?php echo $singleNews->getTitle()?>" style="height:270px">
                                </div>
                                <div class="blog-content">
                                    <h4 class="blog-title" title="<?php echo $singleNews->getTitle()?>"><a href="#"><?php echo substr($singleNews->getTitle(), 0, 35); ?></a></h4>
                                    <div class="blog-info">
                                        <!--a href="#"><i class="fa fa-user"></i>By: </a-->
                                        <a href="#"><i class="fa fa-list"></i><?php echo $singleNews->getCategory();?></a>
                                        <!--a href="#"><i class="fa fa-heart-o"></i>53K</a-->
                                    </div>
                                    <p>
                                    <?php 
                                        //echo substr($singleNews->getBody(), 0, 70);
                                    ?>
                                    </p>
                                    <div class="button">
                                        <a href="<?php echo $config['host'].$singleNews->getUrl(); ?>" class="btn" target="_blank">Read More<i class="fa fa-angle-double-right"></i></a>
                                    </div>
                                </div>
                            </div>
                            <!-- End Single Blog -->
                            </div>
                            
                        <?php endforeach ?>
                    <?php } else { ?>
                            <p>No News </p>
                    <?php } ?>
                    
                    <!--div class="col-lg-4 col-12 grid-item"-->
                        <!-- Single Blog -->
                        <!--div class="single-blog">
                            <div class="blog-head overlay">
                                <div class="date">
                                    <h4>05<span>May</span></h4>
                                </div>
                                <img src="http://via.placeholder.com/800x550" alt="#">
                            </div>
                            <div class="blog-content">
                                <h4 class="blog-title"><a href="blog-single.html">Our teachers egestas erat dignissim</a></h4>
                                <div class="blog-info">
                                    <a href="#"><i class="fa fa-user"></i>By: Admin</a>
                                    <a href="#"><i class="fa fa-list"></i>Academic</a>
                                    <a href="#"><i class="fa fa-heart-o"></i>33K</a>
                                </div>
                                <p>Vivamus volutpat eros pulvinar velit laoreet, sit amet egestas erat dignissim. Et harum quidem rerum facilis est et expedita distinctio</p>
                                <div class="button">
                                    <a href="#" class="btn">Read More<i class="fa fa-angle-double-right"></i></a>
                                </div>
                            </div>
                        </div-->
                        <!-- End Single Blog -->
                    <!--/div-->
                    
                </div>
                
            </div>
        </section>
        <!--/ End Blogs -->    
