<section class="about-us section faq">
			<div class="container">
				<div class="row">
					<!-- Page title -->
					<div class="col-12">
						<div class="about-text">
						<h1 class="page-title">Postgraduate Programme</h1>
						
						</div>
					</div>
					<!-- MSc -->
					<div class="col-12">
						<div class="about-text">
						<h2>Master of Science (MSc) in Theriogenology </h2>
						<p>Candidate must have satisfactorily completed the course work and guided research study approved by the Supervisory Committee. A minimum number of 25 credit units is required for the MSc and 45 for the PhD including credit units for seminar and research.</p>
						<p>Research study and Thesis/Dissertation Presentation: Candidates must have satisfactorily completed the course work and guided research study approved by the Supervisory Committee to be externally defended it. Master's degree candidates will be required to complete 6-12 credit units of research while candidates are to offer24credit units (6cu/semester) of research.</p>
						<p>Seminar: Each postgraduate student is to make a proposal defense and one seminar each semester (1 credit unit/semester) for the duration of his/her study.</p>
						
						<div class="col-lg-10 offset-lg-1 col-12">
						<div class="faq-content">
							<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
								<div class="panel panel-default">
									<!-- Single Faq -->
									<div class="faq-heading"  id="FaqTitle1">
										<h4 class="faq-title">
											<a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#faq1">First Semester</a>
										</h4>
									</div>
									<div id="faq1" class="panel-collapse collapse" role="tabpanel" aria-labelledby="FaqTitle1">
									<div class="faq-body">
                  <table class="table" width="100%">
  <tr>
    <th scope="col">S/N</th>
    <th scope="col">Course Code</th>
    <th scope="col">Course Title</th>
    <th scope="col">Credit Units  </th>
    <th scope="col">Semester</th>
     </tr>
  <tr>
    <td>1</td>
    <td>VMPM  801</td>
    <td><a href="#">	Advanced Histopathology	3(1-6)</a></td>
    <td>2</td>
    <td>
</td>
    </tr>
  <tr>
   <td>2</td>
    <td>VMPT881,883,885</td>
    <td><a href="#">	M.Sc. Seminar </a></td>
    <td>1</td>
    <td>First Semester</td>
  </tr>
  <tr>
    <td>3</td>
    <td>VMPM 980-989</td>
    <td><a href="#">	PhD Seminar Core Specialization Course
</a></td>
    <td>1</td>
    <td>First Semester</td>
  </tr>
  <tr>
    <td>3</td>
    <td>VMPM  803</td>
    <td><a href="#">	Advanced Systemic Pathology I</a></td>
    <td>4</td>
    <td>First Semester</td>
  </tr>
  <tr>
   <td>5</td>
    <td>VMPM  805</td>
    <td><a href="#">	Nutritional Pathology</a></td>
    <td>3</td>
    <td>First Semester</td>
  </tr>
  <tr>
    <td>6</td>
    <td>VMPM  807	</td>
    <td><a href="#">Advanced Poultry Pathology</a> </td>
    <td>3</td>
    <td>Second Semester</td>
  </tr>
  <tr>
    <td>7</td>
    <td>VMPM 802</td>
    <td><a href="#">	Diagnostic Pathology</a></td>
    <td>3</td>
    <td>Second Semester</td>
  </tr>
  
  </table>
									</div>
									</div>
									<!--/ End Single Faq -->
								</div>
								
								
								<div class="panel panel-default">
									<!-- Single Faq -->
									<div class="faq-heading"  id="FaqTitle4">
										<h4 class="faq-title">
											<a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#faq4">Second Semester</a>
										</h4>
									</div>
									<div id="faq4" class="panel-collapse collapse" role="tabpanel" aria-labelledby="FaqTitle4">
									<div class="faq-body">
                  <table width="100%">
  <tr>
    <th scope="col">S/N</th>
    <th scope="col">Course Code</th>
    <th scope="col">Course Title</th>
    <th scope="col">Credit Units  </th>
	<th scope="col">Semester</th>
   </tr>
   <tr>
    <td>8</td>
    <td>VMPM 808</td>
    <td><a href="#">	Advanced Comparative Haematology</a></td>
    <td>3</td>
    <td>Second Semester</td>
  </tr>
   <tr>
    <td>9</td>
    <td>VMPM 880-889	</td>
    <td><a href="#">M.Sc. Seminar </a></td>
    <td>1</td>
    <td>Second Semester</td>
  </tr>
   <tr>
    <td>10</td>
    <td>VMPM 980-989</td>
    <td><a href="#">	PhD Seminar  (1CU/Semester)	<a></td>
    <td>4</td>
    <td>Second Semester</td>
  </tr>
  <tr>
    <td>1</td>
    <td>VMPM 800</td>
    <td><a href="#">		Mechanism of Disease</a></td>
    <td>2</td>
    <td>First Sem</td>
    </tr>
  <tr>
   <td>2</td>
    <td>VMPM 802</td>
    <td><a href="#">		Diagnostic Pathology</a></td>
    <td>3</td>
    <td>First Semester</td>
  </tr>
  <tr>
    <td>3</td>
    <td>VMPM 804</td>
    <td><a href="#">		Oncology</a></td>
    <td>3</td>
    <td>Second Semester</td>
  </tr>
  <tr>
    <td>3</td>
    <td>VMPM 806</td>
    <td><a href="#">Avian Diseases</a></td>
    <td>3</td>
    <td>First Semester</td>
  </tr>
  <tr>
   <td>5</td>
    <td>VMPM 810</td>
    <td><a href="#">Exfoliative Cytology</a></td>
    <td>2</td>
    <td>First Semester</td>
  </tr>
  <tr>
   <td>5</td>
    <td>VMPM 818</td>
    <td><a href="#">Advanced Systemic Pathology II</a></td>
    <td>4</td>
    <td>First Semester</td>
  </tr>
</table>
                </div>
									</div>
									<!--/ End Single Faq -->
								</div>
							
							</div>
						</div>
					</div>
						

					<!-- PhD -->
					<div class="col-12">
						<div class="about-text">
						<h2>Doctor of Philosophy (PhD) in Pathology</h2>
						<p>The vision of the Department is to ensure adequate and sustainable animal production and their products for sustainable human health and development, through efficient and optimal animal reproduction.</p>
						</div>
					</div>
					
					
				</div>

			
			</div>
		</section>
