<!-- Faqs -->
<?php $programmes = $this->programmes;?>
<section class="faq page section">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="section-title">
                            <h2><span> <?php echo $this->title?> </span></h2>
                            <p></p>
                        </div>
                    </div>
                </div>
                <?php
                
                ?>
                <div class="row">
                    <div class="col-lg-10 offset-lg-1 col-12">
                        <div class="faq-content">
                            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                                <?php if (count($programmes) > 0) {?>
                                    <?php $i = 0;?>
                                    <?php foreach ($programmes as $single_programme) : ?>
                            <div class="panel panel-default <?php echo $i==0 ? 'active':'' ?>">
                                    <!-- Single Faq -->
                                    <div class="faq-heading"  id="w<?php echo $single_programme['id']?>">
                                        <h4 class="faq-title">
                                            <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#<?php echo $single_programme['id']?>"><?php echo $single_programme['name']?></a>
                                        </h4>
                                    </div>
                                    <div id="<?php echo $single_programme['id']?>" class="panel-collapse collapse <?php echo $i==0 ? 'show':'' ?>" role="tabpanel" aria-labelledby="w<?php echo $single_programme['id']?>">
                                    <div class="faq-body">
										<p>Duration - <?php echo $single_programme['duration']?></p>
										<?php echo !empty($single_programme['requirements']) ? '<p>Requirements - ' . $single_programme['requirements'].'</p>':'' ?>
                                    </div>
                                    </div>
                                    <!--/ End Single Faq -->
                                </div>
                                        <?php $i = $i + 1;?>
                                    <?php endforeach ?>
                                <?php } else { ?>
                            <p>No information </p>
                                <?php } ?>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--/ End Faqs -->