<section class="about-us section faq">
			<div class="container">
				<div class="row">
					<!-- Page title -->
					<div class="col-12">
						<div class="about-text">
						<h1 class="page-title">Undergraduate Programme</h1>
						
						</div>
					</div>
					<!-- DVM -->
					<div class="col-12">
						<div class="about-text">
						<h2>Doctor of Veterinary Medicine - DVM</h2>
						<p>Duration - 6 years</p>
						<p>The Doctor of Veterinary Medicine program emphasizes the importance of core training in comparative biology and medicine, including all primary clinical disciplines and domestic animal species. Opportunities exist for elective training across a wide variety of more specialized subjects, such as zoo, exotics, and wildlife medicine, marine sciences, clinical nutrition, and various clinical specialties (cardiology, Theriogenology And Production, theriogenology, surgerya and many Other).</p>
						<h3>Graduation Requirement</h3>
						<p>The minimum number of credit units required for graduation by candidate entering 100L is 120, while for those entering at 200 levels is 90. The implication of this is that a student who was admitted at 100 levels must aspire to earn not less than 30 credit units per session. Those who fail to achieve this goal usually end up spending extra sessions in order to qualify for graduation.</p>
						<h3>Course Structure</h3>
          
            <div class="col-lg-10 offset-lg-1 col-12">
						<div class="faq-content">
							<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
								<div class="panel panel-default">
									<!-- Single Faq -->
									<div class="faq-heading"  id="FaqTitle1">
										<h4 class="faq-title">
											<a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#faq1">100 Level Courses</a>
										</h4>
									</div>
									<div id="faq1" class="panel-collapse collapse" role="tabpanel" aria-labelledby="FaqTitle1">
									<div class="faq-body">
                  <table width="100%">
  <tr>
    <th scope="col">S/N</th>
    <th scope="col">Course Code</th>
    <th scope="col">Course Title</th>
    <th scope="col">Credit Units  </th>
    <th scope="col">Semester</th>
     </tr>
  <tr>
    <td>1</td>
    <td>VMPM 401</td>
    <td><a href="#">Clinical Pathology</a></td>
    <td>3</td>
    <td>
</td>
    <tr>
   <td>2</td>
    <td>VMPM 403</td>
    <td><a href="#">	Systemic Pathology</a></td>
    <td>3</td>
    <td>First Semester</td>
  </tr>
  <tr>
    <td>3</td>
    <td>VMPT 403</td>
    <td><a href="#">	Fish Pathology</a></td>
    <td>2</td>
    <td>First Semester</td>
  </tr>
  <tr>
    <td>4</td>
    <td>VMPM 601</td>
    <td><a href="#">Laboratory Animal Diseases</a></td>
    <td>1</td>
    <td>First Semester</td>
  </tr>
  <tr>
   <td>5</td>
    <td>VMPM 603</td>
    <td><a href="#">Necropsy/Avian Clinics</a></td>
    <td>3</td>
    <td>First Semester</td>
  </tr>
  <tr>
    <td>6</td>
    <td>VMPP 600	</td>
    <td><a href="#">Project	4</a> </td>
    <td>4</td>
    <td>First Semester</td>
  </tr>
   
  </table>
									</div>
									</div>
									<!--/ End Single Faq -->
								</div>
								
								
								<div class="panel panel-default">
									<!-- Single Faq -->
									<div class="faq-heading"  id="FaqTitle4">
										<h4 class="faq-title">
											<a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#faq4">200 Level Courses</a>
										</h4>
									</div>
									<div id="faq4" class="panel-collapse collapse" role="tabpanel" aria-labelledby="FaqTitle4">
									<div class="faq-body">
                  <table width="100%">
  <tr>
    <th scope="col">S/N</th>
    <th scope="col">Course Code</th>
    <th scope="col">Course Title</th>
    <th scope="col">Credit Units  </th>
	<th scope="col">Semester</th>
   </tr>
   <tr>
    <td>8</td>
    <td>VMPM 302</td>
    <td><a href="#">Principles of Pathology	</a></td>
    <td>3</td>
    <td>Second Semester</td>
  </tr>
   <tr>
    <td>9</td>
    <td>VMPM 402</td>
    <td><a href="#">Pathology of Infectious Diseases </a></td>
    <td>3</td>
    <td>Second Semester</td>
  </tr>
   <tr>
    <td>10</td>
    <td>VMPM 502</td>
    <td><a href="#">Poultry Diseases and Production	<a></td>
    <td>2</td>
    <td>Second Semester</td>
  </tr>
  <tr>
    <td>1</td>
    <td>VMPM 604</td>
    <td><a href="#">Necropsy/Avian Clinics	3
</a></td>
    <td>3</td>
    <td>Second Sem</td>
    </tr>
  <tr>
   <td>2</td>
    <td>VMPP 600</td>
    <td><a href="#">Project	4</a></td>
    <td>4</td>
    <td>Second Semester</td>
  </tr>
  </table>
                </div>
									</div>
									<!--/ End Single Faq -->
								</div>
							
							</div>
						</div>
					</div>
            
           </div>
						</div>
						
					</div>
					
					
					
				</div>

			
			</div>
		</section>